### ISSUE TITLE
Lack of stored procedure

### ISSUE THREAD

**Issue by kathrine0** [robwise/AmazonProductMetadataParser#2]
Hey, I keep getting error:
Encountered error while executing callable statement 'SQLServerCallableStatement:2'
amazon_product_metadata_parser.output.ProductOutputException: Encountered error while executing callable statement 'SQLServerCallableStatement:2'
    at amazon_product_metadata_parser_example_app.SQLServerOperationsImplExample.executeCallableStatement(SQLServerOperationsImplExample.java:239)
    at amazon_product_metadata_parser_example_app.SQLServerOperationsImplExample.executeBeforeStatements(SQLServerOperationsImplExample.java:56)
    at amazon_product_metadata_parser.output.SQLServer2012.SQLServer2012Output.open(SQLServer2012Output.java:52)
    at amazon_product_metadata_parser.Parser.parse(Parser.java:60)
    at amazon_product_metadata_parser_example_app.Main.run(Main.java:61)
    at amazon_product_metadata_parser_example_app.Main.run(Main.java:21)
    at amazon_product_metadata_parser_example_app.Main.main(Main.java:17)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Could not find stored procedure 'Prepare_Load_Tables'.

Can you provide that missing stored procedure Prepare_Load_Tables?
Thanks

**Comment by robwise** [comment]
Hi @kathrine0, this program is designed to parse the raw data into Java objects and then pass them to SQL Server. What you do in SQL Server from there is completely customizable and specific to how you want to store your data. That's why I left it sort of open-ended for you to create your own SP called `Prepare_Load_Tables` as a sort of pre-run hook to prepare your warehouse.

In case you just want to get up and running quickly and/or it would be helpful to just customize an existing warehouse, here are the various SQL scripts we used to set up our warehouse:

[Warehouse Scripts.zip](https://github.com/robwise/AmazonProductMetadataParser/files/220051/Warehouse.Scripts.zip)

**Comment by kathrine0** [comment]
@robwise thanks a lot for your answer. I'll take a look on the files you uploaded and adjust it to my needs :)
